#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Alci
#
# This file is a part of < https://github.com/aldiboyy/Alci-Userbot
# PLease read the GNU Affero General Public License in
# <https://www.github.com/aldiboyy/Alci-Userbot/blob/main/LICENSE/>.
#
# t.me/WhyzuNotSupport & t.me/WhyzuCH

# start
python3 -m AlciProject
